### PR TITLE
Add Arr::wrap function.

### PR DESCRIPTION
**Pull request by hikouki**
Hi! @SmetDenis 

I'd like to add Arr::wrap function :airplane:

example:
```
Arr.wrap(null)      # => []
Arr.wrap([1, 2, 3]) # => [1, 2, 3]
Arr.wrap(0)         # => [0]
```

### CODE REVIEW

**Comment by SmetDenis** [comment]
Hi @hikouki 

Can you tell me please, what's the difference between
```php
$data = [1,2,3];
$data = Arr::warp($data);
```
and 
```php
$data = [1,2,3];
$data = (array)$data;
```

Best regards, Denis.

**Comment by hikouki** [comment]
Its purpose is wrap, not cast.

such as:

```php
$wrap_data = Arr::wrap(new stdClass());
$cast_data = (array)new stdClass();
```

But, I did not know about array cast behave. thanks!

**Comment by SmetDenis** [comment]
Sorry, I think that's overhead for array() function.

**Comment by hikouki** [comment]
I see.

I expect to use cases :

< Use Arr::wrap >
```php
function eat($something) 
{
    foreach(Arr::wrap($something) as $v) {
        crunch($v);
    }
}
```

< Not use Arr::wrap >
```php
function eat($something) 
{
    if (is_array($something)) {
        foreach(Arr::wrap($something) as $v) {
            crunch($v);
        }
    } else {
        crunch($something);
    }
}
```

Close pull request, If you think not need :smile:

**Comment by SmetDenis** [comment]
Ok, thanks. I understand.
If somebody else says that it really useful - I will add it.

**Pull request merged**
