### PR TITLE
Polyfill mbstring

### PR DESCRIPTION
**Pull request by ProPheT777**

### CODE REVIEW

**Comment by SmetDenis** [comment]
Hi,

Sorry, I don't understand.
Why symfony/polyfill-mbstring better native mbstring extention ?
Can you explain me ?

Thanks.

**Comment by ProPheT777** [comment]
Hey, 

It's a polyfill, it's not intented for replace the native extension, it's used only if mbstring extension is not loaded in php to fallback on this implementation.

**Comment by SmetDenis** [comment]
Ok. Thanks.
I will think about that.

**Comment by SmetDenis** [comment]
I added symfony/polyfill-mbstring to suggest.

**Pull request closed without merging**
